name: Deploy-Docker

on:
  push:
    branches: ["develop", "qa", "prod"]

env:
  GCP_PROJECT: ${{ github.ref_name == 'develop' && 'looply-loo-dev' || github.ref_name == 'qa' && 'looply-loo-qa' || github.ref_name == 'prod' && 'looply-loo-prod' || 'looply-loo-dev' }}
  SERVICE_NAME: ${{ github.ref_name == 'develop' && 'dev-looply-app' || github.ref_name == 'qa' && 'qa-looply-app' || github.ref_name == 'prod' && 'prod-looply-app' || 'dev-looply-app' }}
  IMAGE_NAME: ${{ github.ref_name == 'develop' && 'looply-dev-image' || github.ref_name == 'qa' && 'looply-qa-image' || github.ref_name == 'prod' && 'looply-prod-image' || 'looply-dev-image' }}

jobs:
  Deploying-Docker-Image:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.get_url.outputs.service_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.ref_name == 'develop' && secrets.GCP_SA_KEY_DEV || github.ref_name == 'qa' && secrets.GCP_SA_KEY_QA || secrets.GCP_SA_KEY_PROD }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Check authentication
        run: gcloud auth list

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/looply-repo/${{ env.IMAGE_NAME }}:${{ github.sha }} ./component-library

      - name: Push to Artifact Registry
        run: docker push europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/looply-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/looply-repo/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated

      - name: Get Cloud Run URL
        id: get_url
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region europe-west1 \
            --format='value(status.url)')
          echo "service_url=$URL" >> "$GITHUB_OUTPUT"
