name: Deploy-Docker

on:
  push:
    branches: ["develop", "qa", "prod"]
  pull_request:
    branches:
      - develop

jobs:
  Deploying-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Check authentication
        run: gcloud auth list

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t europe-west2-docker.pkg.dev/looply-loo-dev/looply-repo/looply-dev-image:${{ github.sha }} ./component-library

      - name: Push to Artifact Registry
        run: docker push europe-west2-docker.pkg.dev/looply-loo-dev/looply-repo/looply-dev-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy looply-dev-service \
          --image europe-west2-docker.pkg.dev/looply-loo-dev/looply-repo/looply-dev-image:${{ github.sha }} \
          --region europe-west2 \
          --platform managed \
          --allow-unauthenticated

      - name: Get Cloud Run URL
        run: gcloud run services describe looply-dev-service \
          --region europe-west2 \
          --format='value(status.url)'
